-- tally schema (system MySQL, database `tally`).
--
-- The records live here rather than in the phone's own storage: the device holds a
-- view, not the only copy, so a wipe or a reinstall costs nothing.
--
-- A delete is a real DELETE. Undo is the client re-creating what it still holds in
-- memory for the length of the snackbar — not a row lingering with a flag on it.
-- Deleting a tally cascades to its entries.

SET NAMES utf8mb4;

-- One thing you are keeping count of: a trip, a job, a month.
CREATE TABLE IF NOT EXISTS tallies (
  id         VARCHAR(40)  NOT NULL PRIMARY KEY,       -- generated by the client, so an
  name       VARCHAR(64)  NOT NULL,                   -- entry can be made before a round trip
  currency   VARCHAR(8)   NOT NULL DEFAULT '₪',
  accent     TINYINT      NOT NULL DEFAULT 0,
  created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- One movement of money. Amounts are minor units (agorot/cents) — a running
-- balance must never accumulate float error.
CREATE TABLE IF NOT EXISTS entries (
  id         VARCHAR(40)  NOT NULL PRIMARY KEY,
  tally_id   VARCHAR(40)  NOT NULL,
  direction  ENUM('IN','OUT') NOT NULL,
  amount     BIGINT       NOT NULL,
  note       VARCHAR(255) NOT NULL DEFAULT '',
  category   VARCHAR(32)  NOT NULL DEFAULT 'other',
  at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_tally (tally_id, at),
  CONSTRAINT fk_entry_tally FOREIGN KEY (tally_id) REFERENCES tallies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
